#!/usr/bin/env python3
# coding: utf-8
 
import time
import inspect
import sys
import os
import os.path
import pprint

import numpy
import cupy
import cupyx

import ..aux.cupy_search as cupy_search
import ..aux.cupy_gendatseg_kernels as cupy_gendatseg_kernels
from ..aux.helpers import *
from ..device_config import *

from ..core.hamiltonian import HamiltonianFramework
from ..core.observables import ObservablesFramework

###################################################################################################################################################################################

class phonon_rdm_funcs:
    def __init__(self, HamObj):
        self.searchsorted   = HamObj.searchsorted
        self.get_phonon_occ = HamObj.get_phonon_occ
        self.add_n_to_site  = HamObj.add_n_to_site
        self.QHO_dims       = HamObj.max_HO_dims_v

    ###################################
    # phonon reduced dm from a given vector
    ###################################
    def calculate_rdm(site, whoami, vector):
        occs        = self.get_phonon_occ(whoami, site)
        uniques     = cupy.unique(occs)
        adagger     = self.csr_adagger(whoami, site)
        dim         = self.QHO_dims[site]
        upper_tri   = cupy.zeros((dim, dim), dtype=complex)
        rightvec    = vector.copy()
        for diarow in range(dim):
            vecprod     = numpy.conj(vector) * rightvec
            this_res    = cupy.zeros(dim - diarow, dtype=complex)
            for val in uniques:         # this creates entry rho_{val-diarow,val}
                if val < diarow:
                    continue
                this_res[val-diarow]    = cupy.sum(vecprod[occs == val])
            upper_tri   += cupy.diag(this_res, diarow)
            rightvec    = adagger.dot(rightvec)

        reduced_dm  = upper_tri + cupy.conj(cupy.triu(upper_tri, 1).T)
        return reduced_dm


    ###################################
    # generate phonon adagger csr matrix
    ###################################
    def csr_adagger(basis_states, site):
        plus_inds       = self.generate_mel_adagger_noprefac(basis_states, site)
        inds_to         = self.searchsorted(basis_states, plus_inds, allow_escapes=True)
        mask            = cupy.all(basis_states[inds_to] == plus_inds, axis=1)
        numbs           = len(basis_states)
        return cupy.sparse.coo_matrix((cupy.ones(mask.sum().item()), (inds_to[mask], cupy.arange(numbs, dtype=inds_to.dtype)[mask])), shape=(numbs, numbs)).tocsr()


    ###################################
    # generate creation operator matrix elements, but without sqrt prefactor
    ###################################
    def generate_mel_adagger_noprefac(basis_states, site):
        plus_inds               = basis_states.copy()
        self.add_n_to_site(plus_inds, 1, site)
        return plus_inds


###################################################################################################################################################################################

class HilbertSkeleton(HamiltonianFramework):
    """
    Base object which gives the Hilbert space its basic structure and provides functions to go from one basis state to another.
    Its child HamiltonianObject is arguably the heart of any calculation.
    This object does not contain any Hamiltonian terms itself (which are generated by the object HamiltonianObject); it only "knows" about the Hilbert space structure.
    This object is also wholly agnostic of time, the state vector *and* the current set of basis states. The latter distinguishes it from its child HamiltonianObject.

    This object must provide the following functions:
    - compress_states (args: vector_coo)

    and the following attributes:
    - totwordwidth (integer)
    """
    def __init__(self, nchain, periodic, max_HO_dims, **kwargs):
        super().__init__(**kwargs)
        self.nchain         = nchain
        self.periodic       = bool(periodic)
        with vector_device:
            self.max_HO_dims_v  = self.use_module.asarray(max_HO_dims)
        with whoami_device:
            self.max_HO_dims_w  = self.use_module.asarray(max_HO_dims)

        if self.max_HO_dims_v.max() > 2**self.wordsize:
            raise ValueError("One of the QHO dimensions given as input exceeds %i bits (= %i)." % (self.wordsize, 2**self.wordsize))
        if self.max_HO_dims_v.shape != (self.nchain,):
            raise ValueError("Length of max_HO_dims does not match chain length.")

        self.posbitwidth    = int(self.use_module.ceil(self.use_module.log2(self.nchain)))                          # this is a single int
        with vector_device:
            self.QHObitwidth_v  = cupy.ceil(cupy.log2(self.max_HO_dims_v)).astype(self.dtype)                       # this is a cupy array on vector_device
        with whoami_device:
            self.QHObitwidth_w  = cupy.ceil(cupy.log2(self.max_HO_dims_w)).astype(self.dtype)                       # this is a cupy array on whoami_device
        self.totwordwidth   = int(self.use_module.ceil((self.posbitwidth + self.QHObitwidth_v.sum())/self.wordsize))  # this is a single int

        if self.posbitwidth > 16:
            raise NotImplementedError("Chain lengths requiring more than 16 bits to store (N > 65536) are not yet implemented.")
        if self.periodic:
            raise NotImplementedError("Periodic boundary conditions should not be considered correctly implemented yet.")

    ###################################
    # data segmentation functions, 
    # basic compression/decompression
    ###################################
    def decompress(self, arr):
        maxbytes    = numpy.ceil(numpy.log2(max(self.posbitwidth, self.QHObitwidth_v.max()))/8)
        result      = self.use_module.zeros((len(arr), self.nchain+1), dtype="uint%i" % (8*maxbytes))
        result[:,0] = self.get_pos(arr)
        for i in range(self.nchain):
            result[:,i+1] = self.get_phonon_occ(arr, i)
        return result


    def compress_states(self, raw_basis_states):
        if raw_basis_states.shape[1] != self.nchain+1:
            raise ValueError("Shape of input states does not match chain length.")

        QHObitwidth = self.QHObitwidth_v if raw_basis_states.device == vector_device else self.QHObitwidth_w

        result      = self.use_module.zeros((len(raw_basis_states), self.totwordwidth+1), dtype=self.dtype) # add one column to allow for shape matching when assigning values to the last real column
        lastbit     = self.posbitwidth + QHObitwidth.cumsum()          # index of first bit after the block has ended
        word_i      = (lastbit - QHObitwidth) // self.wordsize         # index of first word containing the block

        if self.totwordwidth > 1:
            ud2             = "uint%i" % (2*self.wordsize)
#            conv            = self.use_module.zeros((len(raw_basis_states), 1), dtype=ud2)
            conv            = raw_basis_states[:,0].astype(ud2) << (2*self.wordsize - self.posbitwidth)
            conv            = conv[None].T
            result[:,:2]    += conv.view(self.dtype)[:,::-1]
            for i in range(self.nchain):
                conv                            = raw_basis_states[:,i+1].astype(ud2) << ((word_i[i]+2)*self.wordsize - lastbit[i])
                conv                            = conv[None].T
                result[:,word_i[i]:word_i[i]+2] += conv.view(self.dtype)[:,::-1]

        else:
            result[:,0]     += raw_basis_states[:,0].astype(self.dtype) << (self.wordsize - self.posbitwidth)
            for i in range(self.nchain):
                result[:,0]     += raw_basis_states[:,i+1].astype(self.dtype) << (self.wordsize - lastbit[i])

        # remove the last column:
        if not self.use_module.all(result[:,-1] == 0):
            raise ValueError("Fatal internal error: In the process of compressing the states, an accessory column was not left unchanged.\nPlease contact your system administrator or pray for relief.")
        result = self.use_module.ascontiguousarray(result[:,:-1])
        return result


    ###################################
    # data segmentation functions, 
    # retrieve values
    ###################################
    def get_phonon_occ(self, arr, site):
        QHObitwidth = self.QHObitwidth_v if arr.device == vector_device else self.QHObitwidth_w
        bit_offset  = self.posbitwidth + QHObitwidth[:site].sum()      # number of bits preceding the block in question (equivalently, index of first relevant bit)
        lastbit     = bit_offset + QHObitwidth[site]                   # index of first bit after the block has ended
        word_i      = bit_offset // self.wordsize                           # index of first word/byte containing the block
        num2bits    = lastbit - self.wordsize*word_i                        # wordsize + number of relevant bits contained in word/byte_i+1 (num2bits == wordsize is "zero")
        numlead     = bit_offset % self.wordsize                            # number of leading bits in word/byte_i that must be trimmed

        result      = arr[:,word_i].copy()
        if numlead != 0:
            result &= (1 << (self.wordsize - numlead)) - 1

        if num2bits < self.wordsize:
            result  >>= self.wordsize - num2bits
        elif num2bits > self.wordsize:
            result  <<= num2bits - self.wordsize
            result  += arr[:,word_i+1] >> (2*self.wordsize-num2bits)
        return result


    def get_pos(self, arr):
        lastbit     = self.posbitwidth
        if lastbit < self.wordsize:
            return arr[:,0] >> (self.wordsize-lastbit)
        elif lastbit == self.wordsize:
            return arr[:,0]
        elif lastbit > self.wordsize:
            if self.wordsize != 8:
                raise NotImplementedError("The chain length seems to exceed 2**16 = 65536, which has not been implemented yet.")
            result  = arr[:,0].astype("uint16")
            result  <<= (lastbit-8)
            result  += (arr[:,1] >> (16-lastbit))
            return result

    def get_phonon_at_exc(self, arr):
        if arr.device   == vector_device:
            return cupy_gendatseg_kernels.get_phonon_at_exc(arr, self.posbitwidth, self.QHObitwidth_v, self.wordsize)
        elif arr.device == whoami_device:
            return cupy_gendatseg_kernels.get_phonon_at_exc(arr, self.posbitwidth, self.QHObitwidth_w, self.wordsize)

    def sum_all_phonons(self, arr, omega=None):
        if type(omega) in (int, float):
            omega   = self.use_module.full(self.nchain, omega, dtype="float64")
        elif isinstance(omega, (list, tuple, numpy.ndarray)) or isinstance(omega, cupy.ndarray):
            omega   = self.use_module.asarray(omega, dtype="float64")
        elif omega is None:
            omega   = cupy.ones(self.nchain, dtype="float64")
        else:
            raise TypeError("Unrecognized type of omega.")
        if arr.device   == vector_device:
            return cupy_gendatseg_kernels.sum_all_phonons(omega, arr, self.posbitwidth, self.QHObitwidth_v, self.wordsize)
        elif arr.device == whoami_device:
            return cupy_gendatseg_kernels.sum_all_phonons(omega, arr, self.posbitwidth, self.QHObitwidth_w, self.wordsize)


    ###################################
    # data segmentation functions, 
    # manipulate values
    ###################################
    def add_n_to_site(self, arr, n, site):
        """
        Takes an array arr and adds (or subtracts) n phonons to site n (to arr itself, not a copy of it).
        This method takes care of rollovers between bytes, but is unsafe with regard to over-/underflows due to floor/ceiling hits.
        """
        if n == 0:
            return

        QHObitwidth = self.QHObitwidth_v if arr.device == vector_device else self.QHObitwidth_w
        bit_offset  = self.posbitwidth + QHObitwidth[:site].sum()      # number of bits preceding the block in question (equivalently, index of first relevant bit)
        lastbit     = bit_offset + QHObitwidth[site]                   # index of first bit after the block has ended
        word_i      = bit_offset // self.wordsize                           # index of first byte containing the block
        num2bits    = lastbit - self.wordsize*word_i                        # wordsize + number of relevant bits contained in word/byte_i+1 (num2bits == wordsize is "zero")

        if num2bits == self.wordsize:
            arr[:,word_i]   += self.dtype(n)
        elif num2bits < self.wordsize:
            arr[:,word_i]   += self.dtype(n << (self.wordsize-num2bits))

        elif num2bits > self.wordsize:
            if wordsize != 8:
                raise NotImplementedError("This method has not been implemented for wordsizes != 8 (consider using add_phonon_to_exc instead).")
            # If the data spans two bytes, add the number to a 16-bit view spanning both bytes.
            # To do that, we must create a contiguous array from arr and also reverse the order due to the CPU/GPU-level little-endian byte ordering.
            # Unfortunately, this requires creating a copy of the two columns in question.
#            arr[:,byte_i:byte_i+2]  = (self.use_module.ascontiguousarray(arr[:,byte_i:byte_i+2][:,::-1]).view("uint16") + n*2**(8-num2bits)).view("uint8")[:,::-1]
            arr[:,word_i:word_i+2]  = (self.use_module.ascontiguousarray(arr[:,word_i:word_i+2][:,::-1]).view("uint16") + self.dtype(n << (16-num2bits))).view("uint8")[:,::-1]
        return


    def add_n_to_pos(self, arr, n):
        """
        Takes an array arr and moves the particle by n sites (acts on arr itself, does not return a copy of it).
        This method takes care of rollovers between bytes, but is unsafe with regard to over-/underflows due to system boundary excursions.
        """
        if n == 0:
            return

        lastbit     = self.posbitwidth
        if lastbit < self.wordsize:
            arr[:,0]    += self.dtype(n << (self.wordsize-lastbit))
        elif lastbit == self.wordsize:
            arr[:,0]    += self.dtype(n)
        elif lastbit > self.wordsize:
            if self.wordsize != 8:
                raise NotImplementedError("The chain length seems to exceed 2**16 = 65536, which has not been implemented yet.")
            # see add_n_to_site for relevant comment on code
            arr[:,:2]   = (self.use_module.ascontiguousarray(arr[:,:2][:,::-1]).view("uint16") + self.dtype(n << (16-lastbit))).view("uint8")[:,::-1]

        return

    def add_phonon_at_exc(self, arr):
        if arr.device   == vector_device:
            cupy_gendatseg_kernels.add_phonon_at_exc(arr, self.posbitwidth, self.QHObitwidth_v, self.wordsize)
        elif arr.device == whoami_device:
            cupy_gendatseg_kernels.add_phonon_at_exc(arr, self.posbitwidth, self.QHObitwidth_w, self.wordsize)

    def rem_phonon_at_exc(self, arr):
        if arr.device   == vector_device:
            cupy_gendatseg_kernels.rem_phonon_at_exc(arr, self.posbitwidth, self.QHObitwidth_v, self.wordsize)
        elif arr.device == whoami_device:
            cupy_gendatseg_kernels.rem_phonon_at_exc(arr, self.posbitwidth, self.QHObitwidth_w, self.wordsize)


###################################################################################################################################################################################

class HamiltonianObject(HilbertSkeleton):
    """
    Partially user-exposed object containing a collection of Hamiltonian-generating functions that can be combined to yield the total Hamiltonian.

    At the very beginning of any simulation, a single instance of this class (or of a child class) is generated,
    which is then repeatedly called to perform all basic actions/generations/manipulations within the Hilbert space.

    Each function must take exactly two inputs, basis_states and raw_map_to—where the latter is used for growing the Hilbert space—
        and return (melpack, debug_info), where melpack must be of the form ((plus_inds, plus_vals, plus_mask), o_star_mask, (minus_inds, minus_vals, minus_mask)). debug_info can be None.
    The terms that shall be used in a given calculation are specified via use_terms.

    This is the lowest-level object whose methods depend on the basis_states. It is agnostic of the state vector.
    """

    ###################################
    # generate hopping matrix elements
    # general, private version first
    ###################################
    def _generate_mel_hopping(self, basis_states, t_sys, order=1, raw_map_to=False):   # basis_states does not have to be sorted for this to work
        if order < 1 or order > self.nchain:
            raise ValueError("Invalid value for order of hopping operator.")
        excpos  = self.get_pos(basis_states)

        # generate the plus side of the hopping (= to the right):
        plus_inds               = basis_states.copy()
        self.add_n_to_pos(plus_inds, order)
        if self.periodic:
            raise NotImplementedError("Periodic hopping not yet implemented.")
        else:         ### for OBC, remove boundary excursions:
            plus_mask               = excpos < self.nchain - order  # remove the ones that began to the right of site (nchain - order - 1)

        # generate the minus side of the coupling (= to the left):
        if not raw_map_to:
            # generate a mask to remove values that occur in both the input and plus_inds:
            o_star_mask             = self._generate_o_star_mask(basis_states, plus_inds, plus_mask)
        else:
            o_star_mask             = slice(None)

        minus_inds              = basis_states[o_star_mask].copy()
        self.add_n_to_pos(minus_inds, -order)
        if self.periodic:
            raise NotImplementedError("Periodic hopping not yet implemented.")
        else:         ### for OBC, remove boundary excursions:
            minus_mask              = excpos[o_star_mask] > order - 1  # remove the ones that began to the left of site (order-1)

        if raw_map_to:
            return plus_inds[plus_mask], minus_inds[minus_mask]

        # generate the values of the matrix elements:
        minus_vals              = t_sys.conjugate()
        plus_vals               = t_sys
        return ((plus_inds, plus_vals, plus_mask), o_star_mask, (minus_inds, minus_vals, minus_mask),), None


    ###################################
    # generate hopping matrix elements
    # wrappers for first- and second-order
    ###################################
    def generate_mel_hopping(self, basis_states, raw_map_to=False):   # basis_states does not have to be sorted for this to work
        return self._generate_mel_hopping(basis_states, self.use_terms["hopping"]["J"], order=1, raw_map_to=raw_map_to)

    def generate_mel_hopping2(self, basis_states, raw_map_to=False):   # basis_states does not have to be sorted for this to work
        return self._generate_mel_hopping(basis_states, self.use_terms["hopping2"]["J2"], order=2, raw_map_to=raw_map_to)


    ###################################
    # generate vibronic coupling matrix elements
    ###################################
    def generate_mel_coupling(self, basis_states, raw_map_to=False):
        max_HO_dims     = self.max_HO_dims_v if basis_states.device == vector_device else self.max_HO_dims_w
        phonon_occs     = self.get_phonon_at_exc(basis_states)
        excpos          = self.get_pos(basis_states)

        # generate the plus side of the coupling:
        plus_inds               = basis_states.copy()
        self.add_phonon_at_exc(plus_inds)
        # add mask for ceiling hits:
        plus_mask               = phonon_occs < max_HO_dims[excpos] - 1

        # generate the minus side of the coupling:
        if not raw_map_to:
            ceiling_hits            = (len(basis_states) - plus_mask.sum())

            # generate a mask to remove values that occur in both the input and plus_inds:
            o_star_mask             = self._generate_o_star_mask(basis_states, plus_inds, plus_mask)
        else:
            o_star_mask             = slice(None)

        minus_inds              = basis_states[o_star_mask].copy()
        self.rem_phonon_at_exc(minus_inds)
        minus_mask              = phonon_occs[o_star_mask] > 0

        if raw_map_to:
            return plus_inds[plus_mask], minus_inds[minus_mask]

        # generate the values of the matrix elements:
        plus_vals               = self.use_terms["coupling"]["g"]             * self.use_module.sqrt(phonon_occs+1, dtype=cupy.float64)
        minus_vals              = self.use_terms["coupling"]["g"].conjugate() * self.use_module.sqrt(phonon_occs[o_star_mask], dtype=cupy.float64)

        return ((plus_inds, plus_vals, plus_mask), o_star_mask, (minus_inds, minus_vals, minus_mask),), ceiling_hits

    ###################################
    # generate diagonal elements
    ###################################
    def generate_diag_vals(self, basis_states):
        diag_vals   = self.use_terms["diag"]["eps_sys"] + self.use_terms["diag"]["hbar_omega"] * self.sum_all_phonons(basis_states)
        if self.use_terms["diag"]["delta_eps"] != 0:
            diag_vals   += self.use_terms["diag"]["delta_eps"] * self.get_pos(basis_states)
        return diag_vals


###################################################################################################################################################################################

class Observables(ObservablesFramework):
    """
    Object responsible for the calculation of any observables over the course of a timeline.
    The functions within this object are time-agnostic, but take the current state-vector as an argument.
    """
    def __init__(self, obs_list, dirname):
        if verbose:
            print("Initializing Observables object...")
        self.dirname    = dirname

        fmode_dict = {"n_b": "ab", "reduced_dm": "ab", "globals": "ab", "diagnostics": "ab", "phonon": "ab"}
        for item in obs_list:
            if not item in  ["H", "hopping", "coupling", "n_b", "reduced_dm", "diagnostics"] + ["phonon%i" % i for i in range(self.HamObj.nchain)] + ["phononproj%i" % i for i in range(self.HamObj.nchain)]:
                raise ValueError('Unrecognized observable "%s".' % item)

        hopstring       = b"hopping " + b''.join([b"hop%i " %i for i in range(self.HamObj.nchain - 1 + int(self.HamObj.periodic))])
        vibstring       = b''.join([b"vib%i " %i for i in range(self.HamObj.nchain)])
        H_file_header   = b"#tag norm " + b"H_tevol " * ("H" in obs_list) + hopstring * ("hopping" in obs_list) + vibstring * ("coupling" in obs_list) + b'\n'
        if "H" in obs_list or "hopping" in obs_list or "coupling" in obs_list:
            with open(os.path.join(self.dirname, "global_operators_real"), 'wb') as H_real_file, open(os.path.join(self.dirname, "global_operators_imag"), 'wb') as H_imag_file:
                H_real_file.write(H_file_header)
                H_imag_file.write(H_file_header)
        if "reduced_dm" in obs_list:
            with open(os.path.join(self.dirname, "dm_files/reduced_dm_real"), 'wb') as dm_real_file, open(os.path.join(self.dirname, "dm_files/reduced_dm_imag"), 'wb') as dm_imag_file:
                numstring = [b"rho_{%i,%i}" % (i, j) for i in range(9) for j in range(9)]
                dm_real_file.write(b"#tag norm " + b' '.join(numstring) + b'\n')
                dm_imag_file.write(b"#tag norm " + b' '.join(numstring) + b'\n')
        if "diagnostics" in obs_list:
            with open(os.path.join(self.dirname, "diagnostics.log"), 'wb') as diag_file:
                diag_file.write(b"#tag norm seconds_since_start post_adapt_norm post_adapt_H expm_converged final_m final_expm_term rel_error_expm numstates ceiling_hits\n")
        if "n_b" in obs_list:
            with open(os.path.join(self.dirname, "local_operators/n_b_real"), 'wb') as n_b_file:
                n_b_file.write(b"#tag norm n^exc_0 n^pho_0 max_HO-n^pho_0 n^exc_1 n^pho_1 max_HO-n^pho_1 etc...\n")

        phononrdm_list  = sorted([i for i in obs_list if i[:6] == "phonon"])
        phononrdm_file_list = []
        if len(phononrdm_list) > 0:
            for obsv in phononrdm_list:
                if obsv[6:10] == "proj":
                    rdmsite     = int(obsv[10:])
                    sname       = "dm_files/phonon_reduced_dm_site%i_projected" % rdmsite
                else:
                    rdmsite     = int(obsv[6:])
                    sname       = "dm_files/phonon_reduced_dm_site%i" % rdmsite
                with open(os.path.join(self.dirname, sname), 'wb') as rdm_phonon_file:
                    n_b_file.write(b"#tag norm rho_00 rho_01 rho_02 etc...\n")
                phononrdm_file_list += [sname,]

#################################### START OF COPY-PASTED CALC FUNCTIONS

    ###################################
    # system reduced dm from a given vector
    ###################################
    def calculate_reduced_dm(self, vector, mindiff=32):
        raise NotImplementedError("The reduced density matrix calculation has not yet been converted to the generalized data segmentation.")
        upper_tri   = self.use_module.zeros((self.HamObj.nchain, self.HamObj.nchain), dtype=self.HamObj.complex_type)
#        cupy.save("last_whoami", self.whoami)
        # use the fact that whoami is lexicographically sorted to determine the break points between the different indices:
        indli       = cupy_search.find_changes_local_single(self.whoami[:,0]).tolist() + [len(self.whoami),]
        lci         = 0
        for left_i in range(self.HamObj.nchain):
            if lci >= len(indli) - 1:
                break
            if self.whoami[indli[lci]][0] != left_i:    # if there is no basis state corresponding to the requested index, skip the iteration
                continue
            left_vec    = vector[indli[lci]:indli[lci+1]]
            left_side   = self.whoami[:,1:][indli[lci]:indli[lci+1]]
            lci         += 1
            rci         = lci   # start testing the position left_index + 1 as the first right_index
            for right_i in range(left_i, self.HamObj.nchain):
                if left_i == right_i:
                    upper_tri[left_i, right_i] = cupy.vdot(left_vec, left_vec)
                elif rci >= len(indli) - 1:
                    break
#                print(left_i, right_i)
                else:
                    if self.whoami[indli[rci]][0] != right_i:    # if there is no basis state corresponding to the requested index, skip the iteration
                        print("(%i, %i) not found. rci, location: %i, %i" % (left_i, right_i, rci, self.whoami[indli[rci]][0]))
                        continue
                    right_vec   = vector[indli[rci]:indli[rci+1]]
                    right_side  = self.whoami[:,1:][indli[rci]:indli[rci+1]]
                    rci         += 1
                    # left_vec are the coefficients matching the left_i
                    # searchsorted(right_side, left_side) returns the indexes of the left_i whoami as they occur in the right_i whoami if they occur, else some value between 0 and 2**32 - 1 depending on certain criteria 
                    # right_side[searchsorted(right_side, left_side)] yields a matching (relative to left_side) value from right_side or some arbitrary value from right_side if there is no matching value
                    # all(right_side[searchsorted(...)] == left_side, axis=1) is a mask that is true only where the values of left_side occur exactly in right_side
                    t0 = time.time()
                    left_search     = cupy_search.searchsorted_multidim_list(left_side, right_side, allow_escapes=True, linear_only=False, mindiff=mindiff)
#                    cupy.cuda.Stream.null.synchronize()
                    if self.debug_verb > searchsorted_multidim_list_timing_level:
                        t1 = time.time()
                        print("This application of searchsorted_multidim_list took %f ms (arg sizes %i, %i)." % ((t1-t0)*1000, left_side.shape[0], right_side.shape[0]))

#                    mask    = left_search < len(left_vec)
#                    upper_tri[left_i, right_i] = ((left_vec[left_search[mask]] * self.use_module.conj(right_vec[mask]))[cupy.all(left_side[left_search[mask]] == right_side[mask], axis=1)]).sum()
                    upper_tri[left_i, right_i] = ((left_vec[left_search] * self.use_module.conj(right_vec))[cupy.all(left_side[left_search] == right_side, axis=1)]).sum()
                    del left_search, right_side
                    mempool.free_all_blocks()

#                    upper_tri[left_i, right_i] = (vector[left_inds][self.use_module.isin(self.whoami[:,1][left_inds], self.whoami[:,1][right_inds], assume_unique=True)] *
#                            self.use_module.conj(vector[right_inds][self.use_module.isin(self.whoami[:,1][right_inds], self.whoami[:,1][left_inds], assume_unique=True)])).sum()
#                upper_tri[left_i, right_i] = (vector[self.whoami[:,0] == left_i] * self.use_module.conj(vector[self.whoami[:,0] == right_i])).sum()
        reduced_dm  = upper_tri + self.use_module.conj(self.use_module.triu(upper_tri, 1).T)
#        cupy.save("sec_to_last_whoami", self.whoami)
        return reduced_dm

    ###################################
    # calculate a partitioned sum, taking into consideration the length of the partitions:
    ###################################
    def calculate_partitioned_sum(self, sumvals, part_constant=5):
        if self.partition_lens.max() < part_constant * self.numstates/self.HamObj.nchain:      # to conserve RAM, only do this if the max partition length is less than part_constant times an equal partitioning:
            return cupy_search.jagged_to_regular(sumvals, self.partition_lens).sum(axis=1)
        else:
            c = 0
            result  = self.use_module.empty(self.HamObj.nchain, dtype=sumvals.dtype)
            for i in range(self.HamObj.nchain):
                result[i]   = sumvals[c:c+self.partition_lens[i]].sum()
                c += self.partition_lens[i]
            return result

    ###################################
    # system population density from a given vector
    ###################################
    def calculate_sys_n_b(self, vector):
        return self.calculate_partitioned_sum(abs(vector)**2)

    ###################################
    # compute avg. HO occs of a given vector
    ###################################
    def calculate_bath_n_b(self, vector):
        # old version, slow:
#        result  = self.use_module.zeros(self.HamObj.nchain)
#        weights = self.use_module.abs(vector)**2
#        for i in range(self.HamObj.nchain):
#            result[i]   = self.HamObj.get_phonon_occ(self.whoami, i).dot(weights)
#        return result
        weights = cupy.abs(vector)**2
        return cupy_gendatseg_kernels.calculate_bath_n_b(weights, cupy.asarray(self.whoami), self.HamObj.posbitwidth, self.HamObj.QHObitwidth_v, self.HamObj.wordsize)

    ###################################
    # compute avg. hopping interaction
    ###################################
    def calculate_hopping(self, vector):
        """
        As long as we don't have an even number of lattice sites with periodic boundary conditions, there is a nice trick
        to calculate the hopping energies using the position projector and the total hopping operator.
        The trick is: hop_i = (... + V_{i-2} - V_{i-1}^\dag) + V_i + (V_{i+1} - V_{i+1}^\dag + V_{i+3} - V_{i+4}^\dag + ...),
        where V_i = <P_i T>, with T being the total hopping operator.
        """
        if self.HamObj.nchain % 2 == 0 and self.HamObj.periodic:
            raise NotImplementedError("This doesn't work for even chain lengths with periodic boundary conditions.")
        allvals = vector.conj() * self.sparse_mats_dict["hopping"].dot(vector)

        V_i = self.calculate_partitioned_sum(allvals)

        if not getattr(self, "hop_board"):
            L               = self.HamObj.nchain
            checkerboard    = self.use_module.array([[1,0] * ((L+1)//2), [0,1] * ((L+1)//2)] * ((L+1)//2))[:L,:L]
            self.hop_board  = self.use_module.triu(checkerboard, 1) + self.use_module.triu(1 - checkerboard).T

        result  = ((1 - self.hop_board) * V_i - self.hop_board * V_i.conj()).sum(axis=1)

        if self.HamObj.periodic:
            return result
        else:
            assert abs(result[-1]) < 1e-12
            return result[:-1]

    ###################################
    # compute avg. coupling interaction
    ###################################
    def calculate_coupling(self, vector):
        allvals     = vector.conj() * self.sparse_mats_dict["coupling"].dot(vector)
        return self.calculate_partitioned_sum(allvals)

    ###################################
    # compute total energy of a state
    ###################################
    def calculate_total_energy(self, vector):
        return self.use_module.vdot(vector, self.total_H(vector)).item()


#################################### CONTINUE HERE

    def calculate_and_write(self, vector):
            ### Start computing observables:
        if "reduced_dm" in obs_list:
            raise NotImplementedError("The reduced density matrix calculation has not yet been converted to the generalized data segmentation.")
            dm_complex  = self.calculate_reduced_dm(vector, mindiff=dm_mindiff)
            if type(dm_complex) != numpy.ndarray:
                dm_complex = cupy.asnumpy(dm_complex)
            dm_real     = dm_complex.real
            dm_imag     = dm_complex.imag
            if self.HamObj.periodic:
                hopping_complex     = numpy.empty(self.HamObj.hopnum)
                hopping_complex[:-1]= 2 * self.HamObj.t_sys * numpy.diag(dm_real, 1)
                hopping_complex[-1] = 2 * self.HamObj.t_sys * dm_real[0,-1]
            else:
                hopping_complex     = 2 * self.HamObj.t_sys * numpy.diag(dm_real, 1)
            n_b_sys     = self.use_module.diag(dm_real)
            if self.debug_verb > 0:
                print("Check 5.1: Calculated reduced density matrix.")
            with open(os.path.join(self.dirname, "dm_files/reduced_dm_real"), fmode_dict["reduced_dm"]) as dm_real_file:
                numpy.savetxt(dm_real_file, numpy.append([t, norm], dm_real.flatten()), newline=" ")
                dm_real_file.write(b'\n')
            with open(os.path.join(self.dirname, "dm_files/reduced_dm_imag"), fmode_dict["reduced_dm"]) as dm_imag_file:
                numpy.savetxt(dm_imag_file, numpy.append([t, norm], dm_imag.flatten()), newline=" ")
                dm_imag_file.write(b'\n')
            if self.debug_verb > 0:
                print("Check 5.2: Saved reduced density matrix.")
            del dm_complex


        for obsv in phononrdm_file_list:
            if obsv[-10:] == "_projected":
                rdmsite     = int(obsv[31:-10])
                mask        = self.HamObj.get_pos(self.whoami) == rdmsite
                phononrdm   = phonon_rdm_funcs(self.HamObj).calculate_rdm(rdmsite, self.whoami[mask], vector[mask])
                del mask
            else:
                rdmsite     = int(obsv[31:])
                phononrdm   = phonon_rdm_funcs(self.HamObj).calculate_rdm(rdmsite, self.whoami, vector)
            with open(os.path.join(self.dirname, obsv), fmode_dict["phonon"]) as rdm_phonon_file:
                numpy.savetxt(rdm_phonon_file, numpy.append([t, norm], cupy.asnumpy(phononrdm).flatten()), newline=" ")
                rdm_phonon_file.write(b'\n')

        if "n_b" in obs_list:
            n_b_result          = self.use_module.empty(self.HamObj.nchain*3)
            if n_b_sys is None:
                n_b_sys         = self.calculate_sys_n_b(vector)
            n_b_result[::3]     = n_b_sys
            n_b_result[1::3]    = self.calculate_bath_n_b(vector)
            n_b_result[2::3]    = self.HamObj.max_HO_dims_v - n_b_result[1::3]
            if type(n_b_result) != numpy.ndarray:
                n_b_result = cupy.asnumpy(n_b_result)
            n_b                 = numpy.append([t, norm], n_b_result)
            if self.debug_verb > 0:
                print("Check 6.1: Calculated occupations.")
            with open(os.path.join(self.dirname, "local_operators/n_b_real"), fmode_dict["n_b"]) as n_b_file:
                numpy.savetxt(n_b_file, n_b, newline=" ")
                n_b_file.write(b'\n')
            if self.debug_verb > 0:
                print("Check 6.2: Saved occupations.")
        if "H" in obs_list:
            H_complex   = self.calculate_total_energy(vector)
            H_real      = H_complex.real
            H_imag      = H_complex.imag
            if self.debug_verb > 0:
                print("Check 7: Calculated energies.")
            H_real_file_savedata += [H_real]
            H_imag_file_savedata += [H_imag]
        if "hopping" in obs_list:
            H_real_file_savedata += [hopping_complex.real.sum()] + list(hopping_complex.real)
            H_imag_file_savedata += [hopping_complex.imag.sum()] + list(hopping_complex.imag)
        if "coupling" in obs_list:
            coupling_complex = self.calculate_coupling(vector)
            if self.debug_verb > 0:
                print("Check 8: Calculated coupling terms.")
            H_real_file_savedata += list(coupling_complex.real)
            H_imag_file_savedata += list(coupling_complex.imag)
        if "coupling" in obs_list or "H" in obs_list or "hopping" in obs_list:
            with open(os.path.join(self.dirname, "global_operators_real"), fmode_dict["globals"]) as H_real_file, open(os.path.join(self.dirname, "global_operators_imag"), fmode_dict["globals"]) as H_imag_file:
                numpy.savetxt(H_real_file, H_real_file_savedata, newline=' ')
                numpy.savetxt(H_imag_file, H_imag_file_savedata, newline=' ')
                H_real_file.write(b'\n')
                H_imag_file.write(b'\n')
            if self.debug_verb > 0:
                print("Check 9: Saved non-local observables data.")
        if (save_first and i == 0) or (save_last and i == len(t_array) - 1) or (save_every is not None and i % save_every == 0):
            self.use_module.save(wf_name_list[i], vector)
            self.use_module.save(wf_name_list[i].replace("wf_file_", "whoami_"), self.whoami)   # this works even if self.whoami is not on current_device
        if "diagnostics" in obs_list:
#   new format:
#                diag_file.write(b"#tag norm seconds_since_start post_adapt_norm post_adapt_H expm_converged final_m final_expm_term rel_error_expm numstates ceiling_hits\n")
            with open(os.path.join(self.dirname, "diagnostics.log"), fmode_dict["diagnostics"]) as diag_file:
                if t == 0:
                    numpy.savetxt(diag_file, [t, norm, time.time() - timeline_start_time, post_adapt_norm, post_adapt_H, 0, 0, 0, 0, self.numstates, 0], newline=" ")
                else:
                    numpy.savetxt(diag_file, [t, norm, time.time() - timeline_start_time, post_adapt_norm, post_adapt_H, expm_converged, final_m, final_expm_term.item(), rel_error_expm.item(), self.numstates, ceiling_hits.item()], newline=" ")
                diag_file.write(b'\n')

        if self.debug_verb > mem_info_level:
            print("Used MiB on vector_device: %1.1f or %1.1f" % (cupy.get_default_memory_pool().used_bytes()/1024**2, numpy.diff(cupy.cuda.Device(vector_device).mem_info)[0]/1024**2))
            with cupy.cuda.Device(whoami_device):
                print("Used MiB on whoami_device: %1.1f or %1.1f" % (cupy.get_default_memory_pool().used_bytes()/1024**2, numpy.diff(cupy.cuda.Device(whoami_device).mem_info)[0]/1024**2))



##################################################################################################################################################################################

class TimeEvolution(TimeEvolutionFramework):
    """
    Concrete class responsible for time evolution, including initial basis and initial state creation.
    This class must necessarily contain the following functions:
    """
    def create_uniform_truncated_basis(self, truncate_d):
        if self.verbose:
            print("Creating initial basis set...", end=' ')
            sys.stdout.flush()
        if truncate_d > self.HamObj.max_HO_dims_v.min():
            raise ValueError("Specified basis truncation value exceeds at least one of the max_HO_dims.")
        if self.HamObj.nchain * truncate_d**self.HamObj.nchain > self.maxstates:
            raise ValueError("Number of states that would result from this value of truncate_d exceeds maxstates!")
        self.write_current_params_to_file(inspect.currentframe())
        raw_whoami      = self.use_module.asarray(cartesian_product(numpy.arange(self.HamObj.nchain, dtype=numpy.uint8), *(numpy.arange(truncate_d, dtype=numpy.uint8) * numpy.ones(self.HamObj.nchain, dtype=numpy.uint8)[None].T)))
        self.whoami     = self.HamObj.compress_states(raw_whoami)
        self.numstates  = self.whoami.shape[0]
        if self.verbose:
            print("Done!")

    def create_nonuniform_basis(self, truncate_d_list, lowest_d_list=None, minpos=0, maxpos=None):
        """
        truncate_d_list:    Number of basis states at given phonon site
        lowest_d_list:      Lowest basis state to construct (defaults to 0 everywhere)
            The highest n at each site is then lowest_d + truncate_d
        minpos:             The leftmost exciton position
        maxpos:             The rightmost exciton position + 1 (i.e., maxpos=nchain is the largest possible)
        """
        function_start_time = time.time()
        if self.verbose:
            print("Creating initial basis set...", end=' ')
            sys.stdout.flush()
        if maxpos is None:
            maxpos = self.HamObj.nchain
        if lowest_d_list is None:
            lowest_d_list = numpy.zeros_like(truncate_d_list)
        if len(truncate_d_list) != self.HamObj.nchain or len(lowest_d_list) != self.HamObj.nchain:
            raise ValueError("Incorrect chain length.")
        if any([lowest_d_list[i] + truncate_d_list[i] > self.HamObj.max_HO_dims_v[i] for i in range(self.HamObj.nchain)]):
            raise ValueError("Specified basis truncation value exceeds at least one of the max_HO_dims.")
        if numpy.product(truncate_d_list) * (maxpos-minpos) > self.maxstates:
            raise ValueError("Number of states that would result from this value of truncate_d exceeds maxstates!")
        if minpos < 0 or maxpos > self.HamObj.nchain or minpos >= maxpos:
            raise ValueError("Invalid minpos or maxpos.")

        self.write_current_params_to_file(inspect.currentframe(), function_start_time)

        nontrivialdim       = numpy.array(truncate_d_list) > 1
        dimlist             = [numpy.arange(lowest_d_list[i], lowest_d_list[i] + truncate_d_list[i], dtype=numpy.uint8) for i in range(self.HamObj.nchain) if nontrivialdim[i]]
        nopad_whoami        = self.use_module.asarray(cartesian_product(numpy.arange(minpos, maxpos, dtype=numpy.uint8), *dimlist))

        raw_whoami          = self.use_module.zeros((nopad_whoami.shape[0], self.HamObj.nchain+1), dtype=numpy.uint8)
        raw_whoami[:,numpy.nonzero(nontrivialdim)[0]+1] = nopad_whoami[:,1:]
        raw_whoami[:,0]     = nopad_whoami[:,0]
        self.whoami         = self.HamObj.compress_states(raw_whoami)
        self.numstates      = self.whoami.shape[0]
        if self.verbose:
            print("Done!")


    def create_moving_gaussian_OBC_basis(self, super_mu, super_sigma, sigma, maxval):
        """
        Create an initial basis consisting of gaussian distributions of phonon occupations around the exciton position.
        super_mu selects the initial exciton position, and super_sigma then sets how much bias is given to the initial position (where numpy.inf corresponds to zero bias and 0 to infinite bias).
        sigma sets how sharp the individual distributions are and maxval sets the highest phonon occupation in total (note that the true max occupation will be slightly higher than maxval, however).
        """
        function_start_time = time.time()
        if self.verbose:
            print("Creating initial basis set...", end=' ')
            sys.stdout.flush()
#        if len(truncate_d_list) != self.HamObj.nchain:
#            raise ValueError("Incorrect chain length.")
#        if numpy.product(truncate_d_list) * self.HamObj.nchain > self.maxstates:
#            raise ValueError("Number of states that would result from this value of truncate_d exceeds maxstates!")
        if maxval >= self.HamObj.max_HO_dims_v.max():
            raise ValueError("Specified basis truncation value exceeds the maximal max_HO_dims.")
        self.write_current_params_to_file(inspect.currentframe())
        def gauss(x, mu, sigma):
            return numpy.exp(-0.5 * ((x-mu)/sigma)**2)
        narr                = numpy.arange(self.HamObj.nchain)
        super_gauss         = 1 + maxval * gauss(narr, super_mu, super_sigma)
        basis_list          = []
        numstates           = 0
        for i in range(self.HamObj.nchain):
            this_d_gauss    = gauss(narr, i, sigma)
            basis_list      += [cartesian_product(*[numpy.arange(super_gauss[i] * this_d_gauss[j], dtype=numpy.uint8) for j in range(self.HamObj.nchain)])]
#            print()
            numstates       += len(basis_list[-1])
            if numstates > self.maxstates:
                raise ValueError("The parameters specified for the initial basis set generate a basis set whose size exceeds maxstates.")

        self.numstates      = numstates
        whoami              = self.use_module.empty((self.numstates, self.HamObj.nchain + 1), dtype=cupy.uint8)
        c = 0
        for i, basis_part in enumerate(basis_list):
            whoami[c:c+len(basis_part),1:]      = self.use_module.asarray(basis_part)
            whoami[c:c+len(basis_part),0]       = i
            c += len(basis_part)

        if self.use_module.any(whoami.max(axis=0) >= self.HamObj.max_HO_dims_v):
            raise ValueError("max_HO_dims exceeded!")
        self.whoami = self.HamObj.compress_states(whoami)

        if self.verbose:
            print("Done!")

    ###################################
    # generate tensor product phonon state (requires an existing basis set)
    ###################################
    def create_tensor_init_state(self, bstates, coeffs, excsite, sites="all"):
        bstates = numpy.asarray(bstates)
        coeffs  = numpy.asarray(coeffs, dtype=complex)
        if sites != "all" and len(sites) > self.HamObj.nchain:
            raise ValueError("Invalid number of sites.")
        if len(bstates) != len(coeffs):
            raise ValueError("Number of coefficients does not match number of states.")

        if sites == "all":
            sitemask    = numpy.ones(self.HamObj.nchain, dtype=bool)
        else:
            sitemask    = numpy.array([i in sites for i in range(self.HamObj.nchain)])
        coeffs  = [coeffs] * sitemask.sum()
        mat     = cartesian_product(*coeffs)
        vector  = mat.prod(axis=1)
        if abs(1 - numpy.linalg.norm(vector)) > 1e-12:
            print(numpy.linalg.norm(vector))
            raise ValueError("State is not normalized, aborting.")

        bmask       = numpy.append([False], sitemask)
        basis       = numpy.zeros((len(vector), self.HamObj.nchain+1))
        basis[:,bmask]  = cartesian_product(*numpy.tile(bstates, (sum(sitemask), 1)))
        basis[:,0]      = excsite

        self.create_initial_vector(vector, basis, auto_normalize=True)

    # End of Hilbert-space-dependent functions
    ###################################################################################################################################################################################


